import os
import shutil
import subprocess

import requests
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("GH_TOKEN", "")
REPO = os.getenv("GH_REPO", "")
BRANCH = os.getenv("BASE_BRANCH", "main")


def _require_env():
    missing = [name for name, value in (("GH_TOKEN", TOKEN), ("GH_REPO", REPO)) if not value]
    if missing:
        raise SystemExit(f"Missing environment variables: {', '.join(missing)}")


def get_alerts():
    url = f"https://api.github.com/repos/{REPO}/code-scanning/alerts?state=open"
    response = requests.get(url, headers=_headers(), timeout=30)
    if response.status_code == 404:
        raise SystemExit("Repository not found or token lacks access")
    if not response.ok:
        raise SystemExit(f"GitHub API error: {response.status_code} {response.text}")
    return response.json()


def get_snippet(path, line):
    raw = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}/{path}"
    response = requests.get(raw, timeout=30)
    if not response.ok:
        raise SystemExit(f"Failed to fetch source: {response.status_code} {response.text}")
    content = response.text.splitlines()
    start = max(0, line - 40)
    end = min(len(content), line + 40)
    return "\n".join(content[start:end])


def ask_llm(rule, description, code):
    prompt = f"""
You are a senior security engineer.

Fix this vulnerability.

Rule: {rule}
Description: {description}

Vulnerable code:
{code}

Return ONLY a unified git diff patch.
Do not add explanations.
Do not modify unrelated code.
"""
    output = _run_ollama(prompt)
    patch = _extract_patch(output)
    if patch:
        return patch
    retry_prompt = f"""
Return ONLY a valid unified git diff patch.
Do not wrap in code fences.
Do not add explanations.

Rule: {rule}
Description: {description}

Vulnerable code:
{code}
"""
    output = _run_ollama(retry_prompt)
    return _extract_patch(output) or output


def create_pr(patch_text):
    patch = _extract_patch(patch_text)
    if not _is_patch(patch):
        print("LLM did not generate a valid patch")
        return

    status = _run_git(["status", "--porcelain"], capture_output=True)
    if status.stdout.strip():
        print("Working tree is not clean. Commit or stash changes and retry.")
        return

    _run_git(["checkout", "-B", "ai/security-fix"], check=True)
    apply = _run_git(["apply", "-"], input_text=patch)
    if apply.returncode != 0:
        print("Patch failed to apply")
        print(apply.stderr.strip() or apply.stdout.strip())
        return

    status = _run_git(["status", "--porcelain"], capture_output=True)
    if not status.stdout.strip():
        print("Patch applied no changes")
        return

    _run_git(["add", "-A"], check=True)
    _run_git(["commit", "-m", "AI security fix"], check=False)
    _run_git(["push", "origin", "ai/security-fix", "--force"], check=False)

    if shutil.which("gh") is None:
        print("GitHub CLI not found. Create PR at:")
        print(f"https://github.com/{REPO}/pull/new/ai/security-fix")
        return

    subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            "AI Security Fix",
            "--body",
            "Automated fix generated by local Ollama security agent",
            "--base",
            BRANCH,
        ],
        check=False,
    )


def _headers():
    return {"Authorization": f"Bearer {TOKEN}", "Accept": "application/vnd.github+json"}


def _is_patch(text):
    if not text:
        return False
    cleaned = text.lstrip()
    return (
        "diff --git " in cleaned
        or (cleaned.startswith("--- ") and "\n+++ " in cleaned and "\n@@ " in cleaned)
    )


def _extract_patch(text):
    if not text:
        return ""
    cleaned = text.strip()
    if cleaned.startswith("```"):
        parts = cleaned.split("```")
        cleaned = max(parts, key=len).strip()
    if "diff --git " in cleaned:
        return cleaned[cleaned.find("diff --git ") :].strip()
    if cleaned.startswith("--- ") and "\n+++ " in cleaned and "\n@@ " in cleaned:
        return cleaned
    return ""


def _run_ollama(prompt):
    result = subprocess.run(
        ["ollama", "run", "deepseek-coder:1.3b-instruct"],
        input=prompt.encode(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise SystemExit(result.stderr.decode() or "Ollama failed to run")
    return result.stdout.decode()


def _run_git(args, input_text=None, capture_output=False, check=False):
    return subprocess.run(
        ["git", *args],
        input=input_text.encode() if input_text is not None else None,
        stdout=subprocess.PIPE if capture_output else None,
        stderr=subprocess.PIPE if capture_output else None,
        check=check,
    )


def main():
    _require_env()
    alerts = get_alerts()
    if not alerts:
        print("No alerts found")
        return

    alert = alerts[0]
    instance = alert.get("most_recent_instance", {}).get("location", {})
    path = instance.get("path")
    line = instance.get("start_line")
    if not path or not line:
        print("Alert missing location data")
        return

    rule = alert.get("rule", {}).get("id", "unknown")
    description = alert.get("rule", {}).get("description", "")

    print("Fixing:", rule, path)

    snippet = get_snippet(path, line)
    patch = ask_llm(rule, description, snippet)
    if _is_patch(patch):
        create_pr(patch)
    else:
        print("LLM did not generate a valid patch")


if __name__ == "__main__":
    main()
