import os
import subprocess

import requests
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("GH_TOKEN", "")
REPO = os.getenv("GH_REPO", "")
BRANCH = os.getenv("BASE_BRANCH", "main")


def _require_env():
    missing = [name for name, value in (("GH_TOKEN", TOKEN), ("GH_REPO", REPO)) if not value]
    if missing:
        raise SystemExit(f"Missing environment variables: {', '.join(missing)}")


def get_alerts():
    url = f"https://api.github.com/repos/{REPO}/code-scanning/alerts?state=open"
    response = requests.get(url, headers=_headers(), timeout=30)
    if response.status_code == 404:
        raise SystemExit("Repository not found or token lacks access")
    if not response.ok:
        raise SystemExit(f"GitHub API error: {response.status_code} {response.text}")
    return response.json()


def get_snippet(path, line):
    raw = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}/{path}"
    response = requests.get(raw, timeout=30)
    if not response.ok:
        raise SystemExit(f"Failed to fetch source: {response.status_code} {response.text}")
    content = response.text.splitlines()
    start = max(0, line - 40)
    end = min(len(content), line + 40)
    return "\n".join(content[start:end])


def ask_llm(rule, description, code):
    prompt = f"""
You are a senior security engineer.

Fix this vulnerability.

Rule: {rule}
Description: {description}

Vulnerable code:
{code}

Return ONLY a unified git diff patch.
Do not add explanations.
Do not modify unrelated code.
"""
    result = subprocess.run(
        ["ollama", "run", "gpt-oss:120b-cloud"],
        input=prompt.encode(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise SystemExit(result.stderr.decode() or "Ollama failed to run")
    return result.stdout.decode()


def create_pr(patch_text):
    with open("fix.patch", "w", encoding="utf8") as f:
        f.write(patch_text)

    subprocess.run(["git", "checkout", "-b", "ai/security-fix"], check=False)
    subprocess.run(["git", "apply", "fix.patch"], check=False)
    subprocess.run(["git", "add", "."], check=False)
    subprocess.run(["git", "commit", "-m", "AI security fix"], check=False)
    subprocess.run(["git", "push", "origin", "ai/security-fix", "--force"], check=False)

    subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            "AI Security Fix",
            "--body",
            "Automated fix generated by local Ollama security agent",
            "--base",
            BRANCH,
        ],
        check=False,
    )


def _headers():
    return {"Authorization": f"Bearer {TOKEN}", "Accept": "application/vnd.github+json"}


def main():
    _require_env()
    alerts = get_alerts()
    if not alerts:
        print("No alerts found")
        return

    alert = alerts[0]
    instance = alert.get("most_recent_instance", {}).get("location", {})
    path = instance.get("path")
    line = instance.get("start_line")
    if not path or not line:
        print("Alert missing location data")
        return

    rule = alert.get("rule", {}).get("id", "unknown")
    description = alert.get("rule", {}).get("description", "")

    print("Fixing:", rule, path)

    snippet = get_snippet(path, line)
    patch = ask_llm(rule, description, snippet)

    if "diff" in patch:
        create_pr(patch)
    else:
        print("LLM did not generate patch")


if __name__ == "__main__":
    main()
